import { Marcellus, Montserrat } from "next/font/google";
import "./globals.css";
// import header component
import Header from "@/components/Header";
import CursorProvider from "@/components/CursorContent";
import Transition from "@/components/Transition";

const marcellus = Marcellus({
  variable: "--font-marcellus",
  weight: "400",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen">
      <body
        className={"${marcellus.variable} ${Montserrat.variable} overflow-x-hidden"}
      >
        <CursorProvider>
          <Transition/>
          <Header />
        </CursorProvider>
        {children}
      </body>
    </html>
  );
}
